version: '2.1'
services:
  api:
    image: django-graphene/api
    container_name: django-graphene-gcp-api
    build:
      context: ./
      dockerfile: ./dev/dockerfiles/gcloud
    environment:
     - DB_NAME=djangographene
     - DB_USER=root
     - DB_PASSWORD=123123
     - DB_HOST=db
     - DB_PORT=3306
     - ELASTICSEARCH_CONNECTION_STRING=http://elastic:changeme@elasticsearch:9200/
    restart: on-failure
    ports:
      - '8008:8000'
    links:
      - db
      - elasticsearch
    volumes:
      - .:/opt/project

  db:
    image: mysql
    container_name: django-graphene-gcp-mysql
    environment:
     - MYSQL_ROOT_PASSWORD=123123
     - MYSQL_DATABASE=djangographene
     - MYSQL_USER=superuser
     - MYSQL_PASSWORD=123123
    volumes:
      - ./dev/data/mysql:/var/lib/mysql
    ports:
      - '3308:3306'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    container_name: django-graphene-gcp-elasticsearch
    environment:
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./dev/data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - '9201:9200'
