# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title', max_length=123)),
                ('description', models.CharField(blank=True, help_text='Description', max_length=500, null=True)),
                ('price', models.IntegerField(blank=True, help_text='Price', null=True)),
                ('name', models.CharField(blank=True, help_text='Owner name', max_length=64, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Phone', max_length=12, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Create')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Update')),
                ('status', django_mysql.models.EnumField(choices=[('PUBLISHED', 'Ad expired'), ('REMOVED', 'Ad removed')], default='PUBLISHED', help_text='Ad status')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=20)),
                ('parent_category', models.ForeignKey(help_text='Parent Category', null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.Category')),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='subcategory',
            field=models.ForeignKey(help_text='Category', on_delete=django.db.models.deletion.CASCADE, to='ads.Category'),
        ),
    ]
